name: CI Maven Project

on: 
 workflow_dispatch:
   inputs:
    TARGET_ENVIRONMENT:
     type: environment
     default: dev        
jobs:
  CI_Non_containerization_build:
    runs-on: ubuntu-latest
    environment: ${{inputs.TARGET_ENVIRONMENT}} 
    steps:
      - name: Checkout
        uses: actions/checkout@4.2.0
      - name: Setup Java JDK 
        uses: actions/setup-java@v3.14.1
        with:
          distribution: microsoft
          java-version: 17
      - name: Build using Maven
        run: mvn --batch-mode --update-snapshots verify     
      - run: mkdir staging && cp target/*.jar staging  
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with: 
          name: Package
          path: staging
