name: reusable workflow

on:
 workflow_dispatch
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
   - name: checkout
     uses: actions/checkout@v4.2.0
   - name: Run reusable build step
     run: echo 'this is reusable one'
